[project]
name = "app"
version = "0.1.0"
description = "ALPS Writer"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "awscli>=1.37.12",
    "boto3>=1.36.12",
    "chainlit>=2.4.1",
    "langchain>=0.3.17",
    "langchain-aws>=0.2.12",
    "markdown>=3.7",
    "pdfplumber>=0.11.5",
    "python-dotenv>=1.0.1",
    "structlog>=25.2.0",
    "tavily-python>=0.5.0",
    "tiktoken>=0.9.0",
]
